#!/usr/bin/env bash
# deploy/bootstrap.sh — idempotent, server-side bootstrap for one country cell (P8b, ADR-0044).
#
# Run once on the VPS (the deploy workflow runs it over SSH, P8c). It mints the *internal*
# operational secrets ON THE BOX and writes them into ./secrets/, which is git-ignored
# (/deploy/secrets/ in .gitignore) and never returned to GitHub. It then brings the Compose
# stack up. Re-running is safe: an existing secret is kept, never rotated — so a second run
# does not lock you out of a database whose password you already deployed.
#
# What it generates (all mode 600, under ./secrets/):
#   pos.env         POSTGRES_USER / POSTGRES_PASSWORD / POSTGRES_DB
#   cloud.toml      pos_cloud config (bind, database_url with the postgres password);
#                   chowned to uid 10001 so the non-root app container can read it
#   nats.conf       NATS JetStream + a token, enforced on the internal network
#   garage.toml     Garage single-node config with an rpc_secret
#   caddy.env       DOMAIN / ACME_EMAIL / CF_DNS_API_TOKEN — the only values that come
#                   from OUTSIDE the box (GitHub secrets in the deploy workflow); required
#                   on the first run, via environment variables (see below)
#   setup-token.txt a one-time super-admin setup token, printed once — it authorizes
#                   enrolling the first super-admin (password + TOTP) through the
#                   first-boot provisioning route (wired in P8c), and is void thereafter
#
# First run needs the reach-the-box + certificate values in the environment, e.g.:
#   DOMAIN=cloud.example.com ACME_EMAIL=ops@example.com CF_DNS_API_TOKEN=xxxx ./bootstrap.sh
# With no purchased domain, use the sslip.io fallback (HTTP-01, no Cloudflare token):
#   DOMAIN=203-0-113-9.sslip.io ACME_EMAIL=ops@example.com ./bootstrap.sh
#
# Set POS_BOOTSTRAP_NO_UP=1 to generate secrets without starting the stack.
set -euo pipefail
umask 077

HERE="$(cd "$(dirname "$0")" && pwd)"
SECRETS="$HERE/secrets"
COMPOSE="$HERE/compose.yml"
APP_UID=10001   # MUST match the poscloud uid created in deploy/Dockerfile.

# 32 (or $1) random bytes as lowercase hex. openssl if present, else /dev/urandom.
rand_hex() {
  local n="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$n"
  else
    od -An -tx1 -N "$n" /dev/urandom | tr -d ' \n'
  fi
}

mkdir -p "$SECRETS"
chmod 700 "$SECRETS"

# 1. PostgreSQL credentials.
if [ ! -e "$SECRETS/pos.env" ]; then
  cat > "$SECRETS/pos.env" <<EOF
POSTGRES_USER=pos
POSTGRES_PASSWORD=$(rand_hex 24)
POSTGRES_DB=poscloud
EOF
  chmod 600 "$SECRETS/pos.env"
  echo "create pos.env"
else
  echo "keep   pos.env"
fi
# Read the credentials back so cloud.toml matches whether or not pos.env was just created.
PG_USER="$(sed -n 's/^POSTGRES_USER=//p' "$SECRETS/pos.env")"
PG_PW="$(sed -n 's/^POSTGRES_PASSWORD=//p' "$SECRETS/pos.env")"
PG_DB="$(sed -n 's/^POSTGRES_DB=//p' "$SECRETS/pos.env")"

# 2. pos_cloud config. The database password lives here (libpq keyword form), never in the
#    environment. The ingest cursor and the retention cron start off — each is armed by
#    editing this file, both deliberate decisions rather than defaults (ADR-0031, ADR-0035).
if [ ! -e "$SECRETS/cloud.toml" ]; then
  cat > "$SECRETS/cloud.toml" <<EOF
# pos_cloud boot config (generated by bootstrap.sh; ADR-0044). Never commit.
bind = "0.0.0.0:8080"
database_url = "host=postgres port=5432 user=$PG_USER password=$PG_PW dbname=$PG_DB"

# The ingest cursor is off until stores publish to JetStream (ADR-0031). To arm it,
# uncomment and use the token from secrets/nats.conf:
# [nats]
# url = "nats://:THE_NATS_TOKEN@nats:4222"
# stream = "POS_FLEET"
# durable = "cloud_ingest"

# retention_days is a legal decision, never a code default (ADR-0035). Set it from the
# country's configured retention period to arm the PII-masking cron; absent = cron off.
# retention_days = 365
EOF
  chmod 600 "$SECRETS/cloud.toml"
  echo "create cloud.toml"
else
  echo "keep   cloud.toml"
fi
# The pos_cloud container runs as uid $APP_UID and must read this 600 file (root ignores
# the mode; the app user does not). bootstrap normally runs as root over SSH.
if chown "$APP_UID:$APP_UID" "$SECRETS/cloud.toml" 2>/dev/null; then
  :
else
  echo "warn   could not chown cloud.toml to $APP_UID (run bootstrap as root); pos_cloud may be unable to read it"
fi

# 3. NATS: JetStream plus a token enforced on the internal network. The monitoring port
#    (8222) stays open for the healthcheck; only client connections need the token.
if [ ! -e "$SECRETS/nats.conf" ]; then
  cat > "$SECRETS/nats.conf" <<EOF
# NATS server config (generated by bootstrap.sh). Never commit.
http_port: 8222
jetstream {
  store_dir: "/data"
}
authorization {
  token: "$(rand_hex 32)"
}
EOF
  chmod 600 "$SECRETS/nats.conf"
  echo "create nats.conf"
else
  echo "keep   nats.conf"
fi

# 4. Garage single node. The rpc_secret is pre-generatable; the S3 access keys are not —
#    Garage mints those at runtime with `garage key create` when the bucket and layout are
#    set up, which lands with backups (P8d).
if [ ! -e "$SECRETS/garage.toml" ]; then
  cat > "$SECRETS/garage.toml" <<EOF
# Garage single-node config (generated by bootstrap.sh; ADR-0031). Never commit.
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
replication_factor = 1
rpc_bind_addr = "[::]:3901"
rpc_secret = "$(rand_hex 32)"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.local"
EOF
  chmod 600 "$SECRETS/garage.toml"
  echo "create garage.toml"
else
  echo "keep   garage.toml"
fi

# 5. Caddy TLS secrets — the only values from outside the box. DOMAIN and ACME_EMAIL are
#    always required; CF_DNS_API_TOKEN is required unless DOMAIN is an *.sslip.io fallback
#    host (which issues over HTTP-01, no Cloudflare token). These are only consulted on the
#    first run; a re-run keeps the existing file and needs no environment.
if [ ! -e "$SECRETS/caddy.env" ]; then
  : "${DOMAIN:?set DOMAIN=your.host (or <vps-ip>.sslip.io) before the first bootstrap}"
  : "${ACME_EMAIL:?set ACME_EMAIL=you@example.com before the first bootstrap}"
  case "$DOMAIN" in
    *.sslip.io) : "${CF_DNS_API_TOKEN:=}" ;;
    *)          : "${CF_DNS_API_TOKEN:?set CF_DNS_API_TOKEN (Cloudflare Zone:DNS:Edit) or use an *.sslip.io DOMAIN}" ;;
  esac
  cat > "$SECRETS/caddy.env" <<EOF
DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL
CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
EOF
  chmod 600 "$SECRETS/caddy.env"
  echo "create caddy.env"
else
  echo "keep   caddy.env"
fi

# 6. One-time super-admin setup token. Authorizes enrolling the first super-admin (password
#    + TOTP) through the first-boot provisioning route (P8c); void once that admin exists.
#    Printed once, here.
if [ ! -e "$SECRETS/setup-token.txt" ]; then
  SETUP_TOKEN="$(rand_hex 32)"
  printf '%s\n' "$SETUP_TOKEN" > "$SECRETS/setup-token.txt"
  chmod 600 "$SECRETS/setup-token.txt"
  echo
  echo "================= ONE-TIME SUPER-ADMIN SETUP TOKEN ================="
  echo "  $SETUP_TOKEN"
  echo "  Enrol the first super-admin with it once, then it is void."
  echo "  (also saved to secrets/setup-token.txt, mode 600)"
  echo "==================================================================="
  echo
else
  echo "keep   setup-token.txt (already generated; void once the first admin is enrolled)"
fi

# 7. Bring the stack up (idempotent). Skipped with POS_BOOTSTRAP_NO_UP=1 or no docker.
if [ "${POS_BOOTSTRAP_NO_UP:-0}" = "1" ]; then
  echo "skip   compose up (POS_BOOTSTRAP_NO_UP=1); run: docker compose -f \"$COMPOSE\" up -d --build"
elif command -v docker >/dev/null 2>&1; then
  echo "up     docker compose up -d --build"
  docker compose -f "$COMPOSE" up -d --build
else
  echo "note   docker not found; when installed, run: docker compose -f \"$COMPOSE\" up -d --build"
fi

echo "done   bootstrap complete"
