# GENERATED FILE — do not edit.
#
# Emitted by dashboard/src/installers.mjs (windowsInstallerTemplate) and regenerated by the
# `dashboard` CI job, which fails if this file and that generator disagree. Edit the generator.
#
# This is the same installer the new-store wizard hands out, with the store's values taken as
# parameters rather than baked in — for a box the console did not create.

#Requires -RunAsAdministrator
<#
.SYNOPSIS
    pos_edge installer for one Windows store.

.DESCRIPTION
    WHAT IT DOES, in order: creates the state directory, puts the binary in the first update
    slot and points `current` at it, writes the bootstrap config, opens the listen port on the
    Private firewall profile, registers the service with the Service Control Manager, sets the
    service-scoped environment (including the store key), sets the failure actions that are what
    bring the box back after an update, and starts it. Idempotent: running it twice is safe and
    re-applies the same layout.

    -SyncKey IS A SECRET. Prefer passing it interactively over leaving it in shell history.

.PARAMETER Binary
    Path to pos-edge.exe.

.PARAMETER StoreId
    The store's ULID, from the console's Stores screen.

.PARAMETER CloudUrl
    The cloud's origin, e.g. https://cloud.example.com.

.PARAMETER SyncKey
    Optional: a store API key (read_config + relay_orders) for the sync loops to present.
    Omit it and the box syncs with the device credential its activation code mints.

.PARAMETER BindPort
    The port the edge listens on. Defaults to 8787.

.PARAMETER Root
    Where the store's state lives.

.PARAMETER CarriedVersion
    The release -Binary is, which the one-file installer (pos-edge install) passes. The summary
    names it beside the release that is running when a re-run keeps the one already there.

.PARAMETER OpenSetup
    Open this box's activation screen in the browser when the service is up. The one-file
    installer (pos-edge install, ADR-0140) passes it; a remote shell has no browser to open.

.PARAMETER AskSyncKey
    With no -SyncKey, ask for a store key in this window. Nothing passes it any more: the
    device credential is enough (ADR-0143). A script run unattended must not stop to ask.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\install-pos-edge.ps1 `
        -Binary .\pos-edge.exe -StoreId 01J... -CloudUrl https://cloud.example.com
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $Binary,

    [Parameter(Mandatory = $true)]
    [string] $StoreId,

    [Parameter(Mandatory = $true)]
    [string] $CloudUrl,

    [string] $SyncKey = '',

    [string] $BindPort = '8787',

    [string] $CarriedVersion = '',

    [switch] $OpenSetup,

    [switch] $AskSyncKey,

    [string] $Root = 'C:\ProgramData\pos-edge'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$service = 'pos-edge'
$expectedStore = $StoreId
$cloudOrigin = $CloudUrl
$installerVersion = $CarriedVersion

# What the summary at the end reports: every step that can leave a store unreachable adds one line
# saying what happened and what to do, so a technician need not read the scroll-back.
$report = New-Object System.Collections.Generic.List[object]
function Add-Check([string] $Level, [string] $Text) {
    $report.Add([pscustomobject]@{ Level = $Level; Text = $Text })
}

if (-not (Test-Path -LiteralPath $Binary -PathType Leaf)) {
    throw "no such binary: $Binary"
}
$Binary = (Resolve-Path -LiteralPath $Binary).Path

# The state directory and the update slot layout (ADR-0055 Amendment 1). `current` is what the
# service runs and what the edge retargets on a successful update; without it the box never
# self-updates.
#
# A box that already has `current` is one the edge is managing: it may be running slot-b after an
# over-the-air update, and re-laying slot-a would point `current` back at whatever binary this
# installer was handed — a silent downgrade of a shop that had updated itself. So the slots are
# laid out once, and a re-run refreshes the config, the service registration and the rescue copy
# without touching the running binary. That is what makes running this twice safe. The one
# exception is a re-run carrying a newer release than the one running, which goes in through the
# edge's own update steps once the service has stopped (below), never by overwriting a slot here.
$bin = Join-Path $Root 'bin'
New-Item -ItemType Directory -Force -Path $Root, $bin | Out-Null

$current = Join-Path $bin 'current'
$kept = Test-Path -LiteralPath $current
if ($kept) {
    Write-Host 'bin\current exists — keeping the installed binary unless this installer carries a newer release (the edge manages its own updates)'
} else {
    Copy-Item -LiteralPath $Binary -Destination (Join-Path $bin 'slot-a') -Force
    # Needs SeCreateSymbolicLinkPrivilege, which an elevated shell has. The edge creates the same
    # link with CreateSymbolicLinkW when it installs an update.
    New-Item -ItemType SymbolicLink -Path $current -Target (Join-Path $bin 'slot-a') -Force | Out-Null
}

# The operator's rescue copy, and what `pos-edge.exe --self-test` is run from by hand. Not what
# the service runs.
Copy-Item -LiteralPath $Binary -Destination (Join-Path $Root 'pos-edge.exe') -Force

# The bootstrap config: which store this is and which cloud to dial. No credential in it.
$config = @"
# pos_edge bootstrap configuration
# Store:  $StoreId
#
# This file tells the store server WHICH store it is and WHICH cloud to dial. It carries no
# credential — that lives in the environment file (or the OS keyring), never here.
# Save it as config.toml beside the pos_edge binary, or point POS_EDGE_CONFIG at its path.

store_id = "$StoreId"
cloud_url = "$CloudUrl"

bind = "0.0.0.0:$BindPort"

# Optional — the LAN IP to advertise in the pairing QR; pin it with a DHCP reservation:
# advertised_ip = "192.168.1.50"

# Absolute on purpose. The Service Control Manager starts a service in C:\Windows\System32,
# and a relative store_path is resolved against the working directory — so the default
# ``store.sqlite`` would put this store's database, and the bin\ update slots beside it, under
# System32. The systemd unit sets WorkingDirectory= and has no such problem.
store_path = "C:\\ProgramData\\pos-edge\\store.sqlite"

# Where this store publishes its committed events. Both values are the whole fleet's, not this
# store's, and they must match the [nats] section of cloud.toml on the cloud box — which is why
# they are generated rather than typed. The server URL is NOT here: it carries the broker token,
# so it lives in the env file below.
#
# Keep this table LAST. Everything above it is a top-level key, and a commented line moved below
# this header would be read as part of [nats] and refused at load.
[nats]
stream = "POS_FLEET"
subject = "pos.fleet.events"

"@
$configPath = Join-Path $Root 'config.toml'
# UTF-8 without a BOM: the TOML parser reads a leading BOM as part of the first key and refuses
# the file. Set-Content -Encoding utf8 writes one on Windows PowerShell 5.1, which is what ships.
[System.IO.File]::WriteAllText($configPath, $config, (New-Object System.Text.UTF8Encoding $false))

# THE PORT, WHICH ON WINDOWS IS NOT OPEN.
#
# Defender Firewall drops an inbound connection to a port no rule names, silently and with no
# log line on either side. So a Windows store installed correctly in every other respect comes
# up, opens its database, writes its pairing URL — and every till on the floor gets a connection
# timeout. That failure is indistinguishable from a broken install, which is why it belongs here
# rather than as a step in a runbook for a technician to type and mis-type.
#
# Private profile only. This port is plain HTTP on the shop LAN, so a rule on the Public profile
# would offer the till API to whatever network the box is plugged into next. Domain is left alone
# deliberately: an estate that joins its boxes to a domain manages this with group policy, and an
# installer should not quietly compete with it.
#
# Idempotent by removal, not by skip: re-running with a different port has to *move* the rule
# rather than leave the old port open beside the new one. A firewall that is switched off, driven
# by policy, or absent from this Windows build is not an install failure - it is warned about and
# skipped, because the service itself is registered and running either way.
$firewallPort = "$BindPort"
$firewallRule = "pos-edge (TCP $firewallPort)"
if (Get-Command -Name New-NetFirewallRule -ErrorAction SilentlyContinue) {
    try {
        # Matches every port this installer has ever opened, not just the one it is opening now.
        $stale = @(Get-NetFirewallRule -DisplayName 'pos-edge (TCP *)' -ErrorAction SilentlyContinue)
        foreach ($rule in $stale) { Remove-NetFirewallRule -Name $rule.Name -ErrorAction Stop }
        $firewall = @{
            DisplayName = $firewallRule
            Direction   = 'Inbound'
            Action      = 'Allow'
            Protocol    = 'TCP'
            LocalPort   = $firewallPort
            Profile     = 'Private'
            Description = 'Pizza 4P''s POS edge: tills and kitchen displays on the shop LAN.'
        }
        New-NetFirewallRule @firewall | Out-Null
        Write-Host "firewall: inbound TCP $firewallPort allowed on the Private profile"
    } catch {
        Write-Warning "could not open TCP $firewallPort ($($_.Exception.Message)). The service will run, but no device on the LAN will reach it until that port is open."
    }
} else {
    Write-Warning "New-NetFirewallRule is not available on this Windows build. Open inbound TCP $firewallPort by hand, or no till will reach this box."
}

# The service. `sc.exe create` fails if it already exists, so a re-run reconfigures instead —
# which is also how the binPath is corrected if the layout moved.
$exists = $null -ne (Get-Service -Name $service -ErrorAction SilentlyContinue)
if ($exists) {
    & sc.exe config $service binPath= "`"$current`"" start= auto | Out-Null
} else {
    & sc.exe create $service binPath= "`"$current`"" start= auto | Out-Null
}
& sc.exe description $service "Pizza 4P's POS edge (store server)" | Out-Null

# WITHOUT THESE TWO PATHS A WINDOWS STORE CANNOT BE PAIRED WITH AT ALL (ADR-0117).
#
# A service started by the Service Control Manager has no console, so everything the edge logs to
# standard output is discarded — including the pairing URL, which is minted once per process start
# and which no route mints a second time. The two variables below are what make a headless box
# diagnosable and pairable:
#
#   * POS_EDGE_LOG_FILE tees the log into a file (the current run, plus the previous run beside it
#     as pos-edge.log.1). It never contains the pairing code, the staff sign-in stream or a
#     credential: the writer excludes those, and raising RUST_LOG cannot change it;
#   * POS_EDGE_PAIRING_FILE is where the pairing URL itself is written, and the edge DELETES it the
#     moment a device redeems the code. Treat it as a five-minute password: read it, pair, and it
#     is gone.
$logPath = Join-Path $Root 'pos-edge.log'
$pairingPath = Join-Path $Root 'pairing-url.txt'

# The environment, service-scoped rather than machine-wide. A machine environment variable is
# readable by every local administrator and shows up in process listings of unrelated services;
# this key is readable only by accounts that can read the service. REG_MULTI_SZ is how SCM passes
# several variables to one service. SCM reads it at start, not on the fly, which is why the
# restart below is not optional.
$environment = @(
    "POS_EDGE_CONFIG=$configPath",
    "POS_EDGE_LOG_FILE=$logPath",
    "POS_EDGE_PAIRING_FILE=$pairingPath",
    'RUST_LOG=info'
)
# Asked for only when -AskSyncKey is given: pasted into this elevated window, the key goes only
# into the service's registry key below — never onto the network, and never into shell history.
if (-not $SyncKey -and $AskSyncKey) {
    $entered = Read-Host -Prompt 'Paste the store key from the console, or press Enter to skip' -AsSecureString
    $SyncKey = [System.Net.NetworkCredential]::new('', $entered).Password.Trim()
}

# An optional store key (read_config + relay_orders). The keyring is the better home for it
# (ADR-0086) and this is the headless bring-up override, exactly as POS_EDGE_SYNC_KEY is on
# Linux. Without one the box syncs with its device credential once it is activated (ADR-0143).
if ($SyncKey) {
    $environment += "POS_EDGE_SYNC_KEY=$SyncKey"
}

# Without an event-bus URL the box publishes its events over HTTPS to the cloud with its device
# credential. Add one only if your cloud runs the NATS stream for store events. It is ONE secret
# shared by the whole fleet, held on the cloud box, so the console cannot fill it in without
# spreading it across every machine in the estate. Recover it on the cloud box, then add it here
# and restart:
#
#   $env = 'POS_EDGE_NATS_URL=tls://:<that token>@<your cloud host>:4222'

$key = "HKLM:\SYSTEM\CurrentControlSet\Services\$service"
New-ItemProperty -Path $key -Name 'Environment' -PropertyType MultiString -Value $environment -Force | Out-Null

# NOT OPTIONAL. This is the Windows counterpart of the unit's Restart=always, and without it the
# store does not come back from an update or a crash. SCM has no always-restart setting — it has
# failure actions, applied when a service looks like it failed:
#
#   * an install retargets bin\current and exits 1, which SCM reads as a failure and restarts
#     five seconds later on the new binary. Exiting 0 would look like a deliberate stop and the
#     shop would stay dark until somebody drove there;
#   * an operator's `sc.exe stop` exits 0 and the service stays stopped, which is what was asked;
#   * a failed start — unreadable config, port already bound, a database that will not open —
#     also exits 1, so the same action retries it rather than leaving a dead service.
#
# reset= 86400 clears the failure count after a day, so three bad days do not exhaust the list.
& sc.exe failure $service reset= 86400 actions= restart/5000/restart/5000/restart/30000 | Out-Null

# Which release this store runs, asked while the old process still answers. A re-run keeps that
# binary unless this installer carries a newer release, which is then put in place below; an
# older or equal one never is (ADR-0140 Amendment 1). Only an answer for this store counts: a
# stray pos-edge for another store says nothing about what bin\current is.
$runningBefore = $null
if ($kept -and $exists) {
    try {
        $before = Invoke-RestMethod -Uri "http://127.0.0.1:$BindPort/healthz" -TimeoutSec 2
        $beforeStore = $before.PSObject.Properties['store_id']
        $beforeVersion = $before.PSObject.Properties['version']
        if ($null -ne $beforeStore -and $beforeStore.Value -eq $expectedStore -and $null -ne $beforeVersion) {
            $runningBefore = [string]$beforeVersion.Value
        }
    } catch {
        $runningBefore = $null
    }
}
$promote = $false
try { $promote = $kept -and ([version][string]$installerVersion) -gt ([version][string]$runningBefore) } catch { $promote = $false }

# Restart rather than start: on a re-run the service is already up on the old environment.
# `sc.exe stop` returns once SCM has sent the control, not once the edge has drained, and a start
# sent while the old process is still stopping is refused. So this waits for STOPPED, bounded; a
# service that has not stopped by then is reported and started anyway.
if ($exists) {
    & sc.exe stop $service | Out-Null
    try {
        (Get-Service -Name $service).WaitForStatus('Stopped', [TimeSpan]::FromSeconds(60))
    } catch {
        Add-Check 'WARN' "the old $service process did not stop within 60 seconds, so the start below may be refused. If the service is not running afterwards: sc.exe start $service"
    }
}

# The pairing file the previous process wrote names a code only that process could redeem, and
# nothing deletes it when the service stops. Left in place, the wait below takes it for this
# start's file: it prints a dead code and moves on before the new process is listening.
Remove-Item -LiteralPath $pairingPath -Force -ErrorAction SilentlyContinue

# A program already listening on the port is a failure the edge can only report by exiting and
# being restarted, over and over. With the service stopped, whatever holds the port now is
# something else, and it is named here, before the start, with what to do about it.
if (Get-Command -Name Get-NetTCPConnection -ErrorAction SilentlyContinue) {
    foreach ($holder in @(Get-NetTCPConnection -State Listen -LocalPort $BindPort -ErrorAction SilentlyContinue)) {
        $process = Get-Process -Id $holder.OwningProcess -ErrorAction SilentlyContinue
        $name = if ($null -ne $process) { $process.ProcessName } else { 'an unknown program' }
        Add-Check 'FAIL' "port $BindPort is already in use by $name (PID $($holder.OwningProcess)), so pos-edge cannot listen on it. Stop that program, or give this store another port."
    }
}

# The newer release goes in through the edge's own update steps, run by the copy this installer
# just wrote: back up the database, stage the binary beside `current`, pass --self-test, commit.
# The outgoing release stays as bin\previous and the new one is on trial exactly as an
# over-the-air install is, so a release that never comes up is replaced by the old one after
# three failed starts, with nobody at the PC. Anything that goes wrong here keeps the old one.
$promoted = $false
if ($promote) {
    $rescue = Join-Path $Root 'pos-edge.exe'
    $env:POS_EDGE_CONFIG = $configPath
    # The edge's refusal arrives on stderr, which Windows PowerShell 5.1 turns into a terminating
    # error under 'Stop' before the exit code can be read.
    $preference = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $promoteOutput = @(& $rescue promote 2>&1 | ForEach-Object { "$_" })
        $promoteCode = $LASTEXITCODE
    } catch {
        $promoteOutput = @("could not run $($rescue): $($_.Exception.Message)")
        $promoteCode = -1
    }
    $ErrorActionPreference = $preference
    Remove-Item -Path Env:POS_EDGE_CONFIG -ErrorAction SilentlyContinue
    $promoteOutput | ForEach-Object { Write-Host $_ }
    if ($promoteCode -eq 0) {
        $promoted = $true
    } else {
        $reason = @($promoteOutput | Where-Object { $_.Trim() }) | Select-Object -Last 1
        if (-not $reason) { $reason = "exit code $promoteCode" }
        Add-Check 'WARN' "could not put $installerVersion in place of $runningBefore, so this PC still runs $runningBefore. The edge said: $reason"
    }
}

$startOutput = (& sc.exe start $service | Out-String).Trim()
# 1056: already running, which is what a start racing a slow stop answers; the checks below say
# whether the store came up.
if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 1056) {
    Add-Check 'FAIL' "sc.exe start $service failed with code $($LASTEXITCODE): $startOutput"
}

& sc.exe query $service
Write-Host ''
Write-Host "pos_edge installed for $StoreId."
Write-Host ''
# The pairing URL, read off the box. The service was started seconds ago, so the code in it is
# live for five minutes from that start; if it has expired, `sc.exe stop pos-edge` and
# `sc.exe start pos-edge` mints a new one. Printed here rather than left for the operator to find,
# because it is the one step between an installed service and a till that works.
#
# The wait is what makes the happy path the one that prints a URL: `sc.exe start` returns as soon
# as SCM has accepted the start, and the edge writes this file after it has opened the store and
# replayed the log, which on a shop-floor PC with a season of history is not instant. Bounded, and
# a timeout falls through to the else branch rather than failing the install — the service is
# registered either way.
$deadline = (Get-Date).AddSeconds(30)
while (-not (Test-Path -LiteralPath $pairingPath) -and (Get-Date) -lt $deadline) {
    Start-Sleep -Milliseconds 500
}

# Which store and release answer on the port. `bin\current` may be a binary the edge installed
# over the air rather than the one this installer was handed, so this is the one place that can
# say what the store runs. It is also what the setup page waits for: SCM reports RUNNING before
# the edge has opened its store and bound the port. Bounded like the wait above.
$health = $null
$deadline = (Get-Date).AddSeconds(30)
while ($null -eq $health -and (Get-Date) -lt $deadline) {
    try { $health = Invoke-RestMethod -Uri "http://127.0.0.1:$BindPort/healthz" -TimeoutSec 2 } catch { Start-Sleep -Milliseconds 500 }
}
if ($null -ne $health) {
    $version = $health.PSObject.Properties['version']
    $version = if ($null -ne $version) { $version.Value } else { 'unknown' }
    $answering = $health.PSObject.Properties['store_id']
    if ($null -ne $answering -and $answering.Value -ne $expectedStore) {
        Add-Check 'FAIL' "port $BindPort is answered by pos-edge $version for store $($answering.Value), not for $expectedStore. Another pos-edge is running on this PC: stop it, then start the service again (sc.exe start $service)."
    } else {
        Add-Check 'ok' "pos-edge $version is answering on port $BindPort for store $expectedStore"
    }
    if ($promoted -and $version -eq $installerVersion) {
        # It came up, which ends its trial. The edge clears the marker itself once it reaches the
        # cloud; a box not activated yet never does, and would count this release's ordinary
        # restarts against it until it put the old one back.
        Remove-Item -LiteralPath (Join-Path $bin 'unconfirmed') -Force -ErrorAction SilentlyContinue
        Add-Check 'ok' "upgraded from $runningBefore to $installerVersion; $runningBefore stays beside it as bin\previous"
    } elseif ($promoted) {
        Add-Check 'WARN' "$installerVersion was put in place of $runningBefore, but $version answers. It is on trial: if it cannot start three times, the service goes back to $runningBefore by itself."
    } elseif ($kept) {
        # Which is newer decides the advice: rolling out an older release is a downgrade, never a fix.
        # No release passed, or one that does not parse ('unknown'), claims neither.
        $order = 0
        try { $order = ([version][string]$installerVersion).CompareTo([version][string]$version) } catch { $order = 0 }
        if ($order -gt 0 -and -not $promote) {
            # Not tried: the old process did not answer before the restart, so its release was not
            # known. It answers now, so a second run can tell.
            Add-Check 'note' "this PC already had pos-edge and runs $version, which was kept because it was not answering when this installer started. Run this installer again to put $installerVersion in place, or roll it out from the console's OTA screen."
        } elseif ($order -gt 0) {
            Add-Check 'note' "this PC already had pos-edge and runs $version, which was kept; the $installerVersion this installer carries went to $Root\pos-edge.exe only. To run $installerVersion here, roll it out from the console's OTA screen."
        } elseif ($order -lt 0) {
            Add-Check 'note' "this PC already had pos-edge and runs $version, newer than the $installerVersion this installer carries, so it was kept."
        } else {
            Add-Check 'note' "this PC already had pos-edge, so the binary it runs was kept (version $version). A newer release reaches this PC over the air, from the console's OTA screen."
        }
    }
} else {
    $state = Get-Service -Name $service -ErrorAction SilentlyContinue
    $state = if ($null -ne $state) { [string]$state.Status } else { 'not registered' }
    Add-Check 'FAIL' "nothing answered on port $BindPort within 30 seconds, and the service is $state. The last lines of $logPath are printed above; the first error in them is the cause."
    if (Test-Path -LiteralPath $logPath) {
        Write-Host "---- the last 20 lines of $logPath ----"
        Get-Content -LiteralPath $logPath -Tail 20 | ForEach-Object { Write-Host $_ }
        Write-Host '----'
    }
    if ($promoted) {
        Add-Check 'note' "$installerVersion was put in place of $runningBefore just now and is on trial: if it cannot start three times, the service goes back to $runningBefore by itself within about two minutes. Run this installer again afterwards to see which release answers."
    }
}

# The adapters a till can reach this PC through: up, and with a default gateway, which is the shop
# LAN and not a VPN or a virtual switch. The pairing URL is completed with their addresses below,
# and theirs are the only firewall profiles that matter.
$lanConfigs = @()
if (Get-Command -Name Get-NetIPConfiguration -ErrorAction SilentlyContinue) {
    try {
        $lanConfigs = @(Get-NetIPConfiguration | Where-Object {
            $_.IPv4DefaultGateway -and $_.IPv4Address -and $_.NetAdapter -and $_.NetAdapter.Status -eq 'Up'
        })
    } catch {
        $lanConfigs = @()
    }
}
$lanIndexes = @($lanConfigs | ForEach-Object { $_.InterfaceIndex })
$lan = @($lanConfigs | ForEach-Object { $_.IPv4Address.IPAddress })

# The firewall rule above is on the Private profile only, and Windows puts a network it has not
# been told about on Public. A store whose LAN is Public passes every check on this PC and no till
# can reach it, which is the failure a technician is least likely to guess. A VPN adapter on
# Public is how it should be, and saying otherwise would teach the technician to ignore this line.
# With no adapter to tell the LAN by, every network is checked.
if (Get-Command -Name Get-NetConnectionProfile -ErrorAction SilentlyContinue) {
    $lanProfiles = @(Get-NetConnectionProfile -ErrorAction SilentlyContinue | Where-Object { $lanIndexes.Count -eq 0 -or $lanIndexes -contains $_.InterfaceIndex })
    foreach ($connection in $lanProfiles) {
        if ([string]$connection.NetworkCategory -eq 'Public') {
            Add-Check 'WARN' "network '$($connection.Name)' ($($connection.InterfaceAlias)) is Public, and port $BindPort is open on Private networks only: no till can reach this PC until it is Private. Fix: Set-NetConnectionProfile -InterfaceIndex $($connection.InterfaceIndex) -NetworkCategory Private"
        } elseif ([string]$connection.NetworkCategory -eq 'DomainAuthenticated') {
            Add-Check 'WARN' "network '$($connection.Name)' is a domain network, where this installer leaves the firewall to group policy: port $BindPort must be allowed there."
        }
    }
}

# Activation needs this PC to reach the cloud over HTTPS, and a TLS handshake fails on a clock that
# is far off. Both are checked now, while someone is at the PC, rather than discovered at /setup.
# Any HTTP answer counts as reachable: it is the network that is in question, not the route.
$cloudHealth = $cloudOrigin.TrimEnd('/') + '/health'
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
$cloudDate = $null
try {
    $probe = Invoke-WebRequest -Uri $cloudHealth -UseBasicParsing -TimeoutSec 10
    $cloudDate = $probe.Headers['Date']
    Add-Check 'ok' "the cloud answers at $cloudOrigin"
} catch {
    $response = $_.Exception.PSObject.Properties['Response']
    if ($null -ne $response -and $null -ne $response.Value) {
        # Windows PowerShell 5.1 hands back a WebResponse, whose headers index by name; PowerShell 7
        # an HttpResponseMessage, whose headers do not. The clock check is a bonus, so it is skipped.
        try { $cloudDate = [string]$response.Value.Headers['Date'] } catch { $cloudDate = $null }
        Add-Check 'ok' "the cloud answers at $cloudOrigin"
    } else {
        Add-Check 'FAIL' "cannot reach the cloud at $cloudOrigin ($($_.Exception.Message)). Activation needs this PC to reach it over HTTPS: check the internet connection, a proxy or a firewall."
    }
}
if ($cloudDate) {
    try {
        $skew = [Math]::Abs(((Get-Date).ToUniversalTime() - [DateTime]::Parse([string]$cloudDate).ToUniversalTime()).TotalMinutes)
        if ($skew -gt 5) {
            Add-Check 'WARN' "this PC's clock is $([Math]::Round($skew)) minutes away from the cloud's; activation and every TLS connection can fail until it is right. Fix: Settings > Time & language > Sync now."
        }
    } catch {}
}

Write-Host 'Next: pair a device on the shop LAN. Open the URL below on it.'
if (Test-Path -LiteralPath $pairingPath) {
    $pairing = (Get-Content -LiteralPath $pairingPath -Raw).Trim()
    # The edge writes the path alone when it cannot name its own address: it listens on every
    # interface and no advertised_ip is set. A device cannot open a bare path, and this box can name
    # its addresses, so the URL is completed with each one that has a default gateway (the shop LAN,
    # not a virtual switch), or with a placeholder that says where to look.
    $urls = @($pairing)
    if ($pairing.StartsWith('/')) {
        $urls = @("http://<this PC's IPv4 address, from ipconfig>:$BindPort$pairing")
        if ($lan.Count -gt 0) {
            $urls = @($lan | ForEach-Object { "http://$($_):$BindPort$pairing" })
        } else {
            Add-Check 'WARN' 'no network adapter with a default gateway is up, so nothing on the shop LAN can reach this PC yet. Connect it to the shop network, then read the pairing file again.'
        }
    }
    Write-Host ''
    foreach ($url in $urls) { Write-Host $url }
    Write-Host ''
    Write-Host "That code lives five minutes and pairs one device. For the next device: sc.exe stop $service; sc.exe start $service — then read $pairingPath again."
} else {
    Write-Host "The pairing URL is not there yet. Read $pairingPath in a moment, or $logPath for why the service did not get that far; the address is http://<this box>:$BindPort/."
    Add-Check 'WARN' "no pairing code was written within 30 seconds; $pairingPath appears once the store is up."
}

# Everything above, in one place: a technician reads this and not the scroll-back. Nothing here
# fails the install, because the service is registered either way and most of these are fixed
# on the PC, not by running the installer again.
Write-Host ''
Write-Host 'pos-edge setup summary'
foreach ($check in $report) {
    $colour = switch ($check.Level) { 'ok' { 'Green' } 'FAIL' { 'Red' } 'WARN' { 'Yellow' } default { 'Gray' } }
    Write-Host ('  {0,-5} {1}' -f $check.Level, $check.Text) -ForegroundColor $colour
}
$failures = @($report | Where-Object { $_.Level -eq 'FAIL' }).Count
if ($failures -gt 0) {
    Write-Host "  $failures problem(s) above stop this store from working; each line says what to do." -ForegroundColor Red
}
Write-Host ''
if ($SyncKey) { Write-Host 'The store key is now in the service registry key. Clear it from your shell history.' }

# The next step is activation, on this box's own screen (ADR-0050). The one-file installer asks
# for it; a technician on a remote shell has no browser here, so it is a switch, not a default.
if ($OpenSetup) {
    $setupUrl = "http://localhost:$BindPort/setup"
    Write-Host "Next: activate this store at $setupUrl with the code from the console."
    try { Start-Process $setupUrl } catch { Write-Host "Open $setupUrl in a browser on this PC." }
}
