# GENERATED FILE — do not edit.
#
# Emitted by dashboard/src/installers.mjs (printAgentInstallerTemplate) and regenerated by the
# `dashboard` CI job, which fails if this file and that generator disagree. Edit the generator.
#
# Installs pos_print_agent on the terminal whose USB or serial port reaches a printer
# (ADR-0112). Only stores whose edge runs somewhere other than the shop need one.

#Requires -RunAsAdministrator
<#
.SYNOPSIS
    pos_print_agent installer for one terminal.

.DESCRIPTION
    WHAT IT DOES, in order: creates the state directory, copies the binary, writes the config,
    registers the service, puts the device token in the service's own environment, sets the
    failure actions that bring the terminal back after a crash, and starts it. Idempotent:
    running it twice is safe.

    BEFORE RUNNING IT: pair this machine with the store's edge and have a manager bind it to the
    terminal entry the console created. Until both are done the agent runs and is told, on every
    claim, that it answers for no print agent.

    -DeviceToken IS A SECRET. Prefer passing it interactively over leaving it in shell history.

.PARAMETER Binary
    Path to pos_print_agent.exe.

.PARAMETER EdgeUrl
    The store's edge, e.g. http://192.0.2.10:8787 on a shop LAN, or https://store.example.com
    for an edge that runs somewhere else.

.PARAMETER DeviceToken
    The bearer token this machine was issued when it was paired with that edge.

.PARAMETER Root
    Where the agent's state lives.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\install-pos-print-agent.ps1 `
        -Binary .\pos_print_agent.exe -EdgeUrl http://192.0.2.10:8787 -DeviceToken <token>
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $Binary,

    [Parameter(Mandatory = $true)]
    [string] $EdgeUrl,

    [Parameter(Mandatory = $true)]
    [string] $DeviceToken,

    [string] $Root = 'C:\ProgramData\pos-print-agent'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$service = 'pos-print-agent'

if (-not (Test-Path -LiteralPath $Binary -PathType Leaf)) {
    throw "no such binary: $Binary"
}
$Binary = (Resolve-Path -LiteralPath $Binary).Path

# No update slots: the agent is not over-the-air updatable, and reinstalling it costs at most one
# duplicated ticket (ADR-0112). The service runs the copy under $Root, so replacing the agent is
# re-running this script with a newer binary.
New-Item -ItemType Directory -Force -Path $Root | Out-Null
$installed = Join-Path $Root 'pos_print_agent.exe'
$running = $null -ne (Get-Service -Name $service -ErrorAction SilentlyContinue)
if ($running) { & sc.exe stop $service | Out-Null; Start-Sleep -Seconds 2 }
Copy-Item -LiteralPath $Binary -Destination $installed -Force

# The config. Readable by whoever is diagnosing a printer, and holding no credential.
$config = @"
# pos_print_agent — generated by the console. Safe to read; holds no credential.
#
# The device token is NOT here: it is a credential, and it reaches the agent through the
# environment (POS_PRINT_AGENT_TOKEN on Linux, the service's own registry key on Windows).

# The store's edge. http on a shop LAN, https for an edge that runs somewhere else
# (ADR-0110 made that a deployment axis, and both are real).
edge_url = "$EdgeUrl"

# One id per printer: the last job written successfully, so a redelivered job after a lost
# acknowledgement is recognised rather than reprinted (ADR-0112).
state_path = "C:\\ProgramData\\pos-print-agent\\state.json"

"@
$configPath = Join-Path $Root 'print-agent.toml'
# UTF-8 without a BOM: the TOML parser reads a leading BOM as part of the first key and refuses
# the file. Set-Content -Encoding utf8 writes one on Windows PowerShell 5.1, which is what ships.
[System.IO.File]::WriteAllText($configPath, $config, (New-Object System.Text.UTF8Encoding $false))

if ($running) {
    & sc.exe config $service binPath= "`"$installed`"" start= auto | Out-Null
} else {
    & sc.exe create $service binPath= "`"$installed`"" start= auto | Out-Null
}
& sc.exe description $service "Pizza 4P's print agent (writes this terminal's printers)" | Out-Null

# Service-scoped rather than machine-wide, for the reason the edge's installer gives at length: a
# machine environment variable is readable by every local administrator and shows up in process
# listings of unrelated services. The device token belongs in neither place.
$environment = @(
    "POS_PRINT_AGENT_CONFIG=$configPath",
    "POS_PRINT_AGENT_TOKEN=$DeviceToken",
    'RUST_LOG=info'
)
$key = "HKLM:\SYSTEM\CurrentControlSet\Services\$service"
New-ItemProperty -Path $key -Name 'Environment' -PropertyType MultiString -Value $environment -Force | Out-Null

# NOT OPTIONAL, exactly as on the edge. SCM has no always-restart setting; without these actions a
# crashed agent stays dead, the kitchen prints nothing, and the till keeps reporting
# QUEUED_TO_AGENT because the queue is doing its job. reset= 86400 clears the failure count after
# a day, so three bad days do not exhaust the list.
& sc.exe failure $service reset= 86400 actions= restart/5000/restart/5000/restart/30000 | Out-Null

& sc.exe start $service | Out-Null
& sc.exe query $service
Write-Host ''
Write-Host 'pos_print_agent installed.'
Write-Host 'Next: on the till, sign in as a manager and bind this device to its terminal entry.'
Write-Host 'The token is now in the service registry key. Clear it from your shell history.'
