# GENERATED FILE — do not edit.
#
# Emitted by dashboard/src/installers.mjs (windowsInstallerTemplate) and regenerated by the
# `dashboard` CI job, which fails if this file and that generator disagree. Edit the generator.
#
# This is the same installer the new-store wizard hands out, with the store's values taken as
# parameters rather than baked in — for a box the console did not create.

#Requires -RunAsAdministrator
<#
.SYNOPSIS
    pos_edge installer for one Windows store.

.DESCRIPTION
    WHAT IT DOES, in order: creates the state directory, puts the binary in the first update
    slot and points `current` at it, writes the bootstrap config, registers the service with
    the Service Control Manager, sets the service-scoped environment (including the store key),
    sets the failure actions that are what bring the box back after an update, and starts it.
    Idempotent: running it twice is safe and re-applies the same layout.

    -SyncKey IS A SECRET. Prefer passing it interactively over leaving it in shell history.

.PARAMETER Binary
    Path to pos-edge.exe.

.PARAMETER StoreId
    The store's ULID, from the console's Stores screen.

.PARAMETER CloudUrl
    The cloud's origin, e.g. https://cloud.example.com.

.PARAMETER SyncKey
    The store's scoped API key (read_config + relay_orders). Omit to install without one:
    the store trades, and config sync and the order relay refuse until a key is installed.

.PARAMETER BindPort
    The port the edge listens on. Defaults to 8787.

.PARAMETER Root
    Where the store's state lives.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\install-pos-edge.ps1 `
        -Binary .\pos-edge.exe -StoreId 01J... -CloudUrl https://cloud.example.com
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $Binary,

    [Parameter(Mandatory = $true)]
    [string] $StoreId,

    [Parameter(Mandatory = $true)]
    [string] $CloudUrl,

    [string] $SyncKey = '',

    [string] $BindPort = '8787',

    [string] $Root = 'C:\ProgramData\pos-edge'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$service = 'pos-edge'

if (-not (Test-Path -LiteralPath $Binary -PathType Leaf)) {
    throw "no such binary: $Binary"
}
$Binary = (Resolve-Path -LiteralPath $Binary).Path

# The state directory and the update slot layout (ADR-0055 Amendment 1). `current` is what the
# service runs and what the edge retargets on a successful update; without it the box never
# self-updates.
#
# A box that already has `current` is one the edge is managing: it may be running slot-b after an
# over-the-air update, and re-laying slot-a would point `current` back at whatever binary this
# installer was handed — a silent downgrade of a shop that had updated itself. So the slots are
# laid out once, and a re-run refreshes the config, the service registration and the rescue copy
# without touching the running binary. That is what makes running this twice safe.
$bin = Join-Path $Root 'bin'
New-Item -ItemType Directory -Force -Path $Root, $bin | Out-Null

$current = Join-Path $bin 'current'
if (Test-Path -LiteralPath $current) {
    Write-Host 'bin\current exists — leaving the installed binary alone (the edge manages its own updates)'
} else {
    Copy-Item -LiteralPath $Binary -Destination (Join-Path $bin 'slot-a') -Force
    # Needs SeCreateSymbolicLinkPrivilege, which an elevated shell has. The edge creates the same
    # link with CreateSymbolicLinkW when it installs an update.
    New-Item -ItemType SymbolicLink -Path $current -Target (Join-Path $bin 'slot-a') -Force | Out-Null
}

# The operator's rescue copy, and what `pos-edge.exe --self-test` is run from by hand. Not what
# the service runs.
Copy-Item -LiteralPath $Binary -Destination (Join-Path $Root 'pos-edge.exe') -Force

# The bootstrap config: which store this is and which cloud to dial. No credential in it.
$config = @"
# pos_edge bootstrap configuration
# Store:  $StoreId
#
# This file tells the store server WHICH store it is and WHICH cloud to dial. It carries no
# credential — that lives in the environment file (or the OS keyring), never here.
# Save it as config.toml beside the pos_edge binary, or point POS_EDGE_CONFIG at its path.

store_id = "$StoreId"
cloud_url = "$CloudUrl"

bind = "0.0.0.0:$BindPort"

# Optional — the LAN IP to advertise in the pairing QR; pin it with a DHCP reservation:
# advertised_ip = "192.168.1.50"

# Absolute on purpose. The Service Control Manager starts a service in C:\Windows\System32,
# and a relative store_path is resolved against the working directory — so the default
# ``store.sqlite`` would put this store's database, and the bin\ update slots beside it, under
# System32. The systemd unit sets WorkingDirectory= and has no such problem.
store_path = "C:\\ProgramData\\pos-edge\\store.sqlite"

# Where this store publishes its committed events. Both values are the whole fleet's, not this
# store's, and they must match the [nats] section of cloud.toml on the cloud box — which is why
# they are generated rather than typed. The server URL is NOT here: it carries the broker token,
# so it lives in the env file below.
#
# Keep this table LAST. Everything above it is a top-level key, and a commented line moved below
# this header would be read as part of [nats] and refused at load.
[nats]
stream = "POS_FLEET"
subject = "pos.fleet.events"

"@
$configPath = Join-Path $Root 'config.toml'
# UTF-8 without a BOM: the TOML parser reads a leading BOM as part of the first key and refuses
# the file. Set-Content -Encoding utf8 writes one on Windows PowerShell 5.1, which is what ships.
[System.IO.File]::WriteAllText($configPath, $config, (New-Object System.Text.UTF8Encoding $false))

# The service. `sc.exe create` fails if it already exists, so a re-run reconfigures instead —
# which is also how the binPath is corrected if the layout moved.
$exists = $null -ne (Get-Service -Name $service -ErrorAction SilentlyContinue)
if ($exists) {
    & sc.exe config $service binPath= "`"$current`"" start= auto | Out-Null
} else {
    & sc.exe create $service binPath= "`"$current`"" start= auto | Out-Null
}
& sc.exe description $service "Pizza 4P's POS edge (store server)" | Out-Null

# The environment, service-scoped rather than machine-wide. A machine environment variable is
# readable by every local administrator and shows up in process listings of unrelated services;
# this key is readable only by accounts that can read the service. REG_MULTI_SZ is how SCM passes
# several variables to one service. SCM reads it at start, not on the fly, which is why the
# restart below is not optional.
$environment = @(
    "POS_EDGE_CONFIG=$configPath",
    'RUST_LOG=info'
)
# The scoped store key (read_config + relay_orders). The keyring is the better home for it
# (ADR-0086) and this is the headless bring-up override, exactly as POS_EDGE_SYNC_KEY is on
# Linux. Without one the store still trades; config sync and the order relay refuse.
if ($SyncKey) {
    $environment += "POS_EDGE_SYNC_KEY=$SyncKey"
} else {
    Write-Warning 'no -SyncKey given: config sync and the order relay will refuse until one is installed'
}

# The event-bus URL is deliberately absent. Unlike the store key it is ONE secret shared by the
# whole fleet, held on the cloud box, so the console cannot fill it in without spreading it across
# every machine in the estate. Recover it on the cloud box, then add it here and restart:
#
#   $env = 'POS_EDGE_NATS_URL=tls://:<that token>@<your cloud host>:4222'
#
# Until it is set the edge logs that POS_EDGE_NATS_URL is unset and the outbox holds — the store
# trades either way.

$key = "HKLM:\SYSTEM\CurrentControlSet\Services\$service"
New-ItemProperty -Path $key -Name 'Environment' -PropertyType MultiString -Value $environment -Force | Out-Null

# NOT OPTIONAL. This is the Windows counterpart of the unit's Restart=always, and without it the
# store does not come back from an update or a crash. SCM has no always-restart setting — it has
# failure actions, applied when a service looks like it failed:
#
#   * an install retargets bin\current and exits 1, which SCM reads as a failure and restarts
#     five seconds later on the new binary. Exiting 0 would look like a deliberate stop and the
#     shop would stay dark until somebody drove there;
#   * an operator's `sc.exe stop` exits 0 and the service stays stopped, which is what was asked;
#   * a failed start — unreadable config, port already bound, a database that will not open —
#     also exits 1, so the same action retries it rather than leaving a dead service.
#
# reset= 86400 clears the failure count after a day, so three bad days do not exhaust the list.
& sc.exe failure $service reset= 86400 actions= restart/5000/restart/5000/restart/30000 | Out-Null

# Restart rather than start: on a re-run the service is already up on the old environment.
if ($exists) { & sc.exe stop $service | Out-Null; Start-Sleep -Seconds 2 }
& sc.exe start $service | Out-Null

& sc.exe query $service
Write-Host ''
Write-Host "pos_edge installed for $StoreId."
Write-Host "Next: open http://<this box>:$BindPort/ on a device on the shop LAN and pair it."
if ($SyncKey) { Write-Host 'The store key is now in the service registry key. Clear it from your shell history.' }
